/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import code.AlfabetoTotal;
import code.TuringMachine;
import code.Funcao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import utilities.GUIMessage;

/**
 *
 * @author Vinicios
 */
public class MainScreen extends javax.swing.JFrame {

    // Model lists
    private DefaultListModel mlist_fita;
    private DefaultListModel mlist_cabecote;
    private DefaultListModel mlist_estados;
    private DefaultListModel mlist_funcoes;
    private DefaultListModel mlist_alfabetos;
    private DefaultListModel mlist_alfabetosAuxiliares;
    private DefaultTableModel model;

    static TuringMachine maquina;
    private DefaultListCellRenderer renderer;

    private static List<String> listaEstados;
    private static List<Funcao> listaFuncoes;
    private static AlfabetoTotal alfabetos;

    private List<String> jlTabelaColunas;

    /**
     * Creates new form Tela
     */
    public MainScreen() {
        initComponents();
        maquina = new TuringMachine();
        mlist_fita = new DefaultListModel();
        mlist_cabecote = new DefaultListModel();
        mlist_estados = new DefaultListModel();
        mlist_funcoes = new DefaultListModel();
        mlist_alfabetos = new DefaultListModel();
        mlist_alfabetosAuxiliares = new DefaultListModel();
        model = (DefaultTableModel) jtTabela.getModel();
        model.setColumnCount(0);
//
//        //jlFita.setModel(list_fita);
//        // jlCabecote.setModel(list_cabecote);
//        jbLimparFita.setEnabled(false);
//        //renderer = (DefaultListCellRenderer) jlFita.getCellRenderer();
//        renderer.setHorizontalAlignment(SwingConstants.CENTER);
//        //renderer = (DefaultListCellRenderer) jlCabecote.getCellRenderer();
//        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        listaEstados = new ArrayList();
        listaFuncoes = new ArrayList();
        alfabetos = new AlfabetoTotal();

        /*
         Vinculando os models as Jlists...
         */
        jlEstados.setModel(mlist_estados);
        jlFuncoes.setModel(mlist_funcoes);
        jlAlfabetos.setModel(mlist_alfabetos);
        jlAuxiliares.setModel(mlist_alfabetosAuxiliares);

        jlTabelaColunas = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTuringMachine = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtFita = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpBuscas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfBuscarFrase = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jpFuncoes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbTelaFuncao = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlFuncoes = new javax.swing.JList<>();
        jpEstados = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbTelaEstado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlEstados = new javax.swing.JList<>();
        jpAlfabeto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlAlfabetos = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlAuxiliares = new javax.swing.JList<>();
        jbInserirAlfabeto = new javax.swing.JButton();
        jbDefinirAlfabetoAuxiliar = new javax.swing.JButton();
        jpFita = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfInserirFita = new javax.swing.JTextField();
        jbInserirFita = new javax.swing.JButton();
        jbLimparFita = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turing Machine");

        jpTuringMachine.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtTabela.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabela.setRowSelectionAllowed(false);
        jtTabela.setShowHorizontalLines(false);
        jtTabela.setShowVerticalLines(false);
        jtTabela.getTableHeader().setResizingAllowed(false);
        jtTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtTabela);

        jLabel5.setText("Tabela de Transições:");

        jtFita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtFita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "-", "-", "-", "(Cabeçote)", "-", "-", "-"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFita.setRowSelectionAllowed(false);
        jtFita.setShowHorizontalLines(false);
        jtFita.setShowVerticalLines(false);
        jtFita.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jtFita);

        jLabel3.setText("Fita:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Turing Machine");

        jpBuscas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Buscar uma frase na fita");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBuscasLayout = new javax.swing.GroupLayout(jpBuscas);
        jpBuscas.setLayout(jpBuscasLayout);
        jpBuscasLayout.setHorizontalGroup(
            jpBuscasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jtfBuscarFrase)
                    .addComponent(jbBuscar))
                .addContainerGap())
        );
        jpBuscasLayout.setVerticalGroup(
            jpBuscasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfBuscarFrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpTuringMachineLayout = new javax.swing.GroupLayout(jpTuringMachine);
        jpTuringMachine.setLayout(jpTuringMachineLayout);
        jpTuringMachineLayout.setHorizontalGroup(
            jpTuringMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTuringMachineLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(191, 191, 191))
            .addGroup(jpTuringMachineLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpTuringMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpBuscas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(16, 16, 16))
        );
        jpTuringMachineLayout.setVerticalGroup(
            jpTuringMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTuringMachineLayout.createSequentialGroup()
                .addGroup(jpTuringMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addComponent(jpBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpFuncoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Funções");

        jbTelaFuncao.setText("Nova Função");
        jbTelaFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTelaFuncaoActionPerformed(evt);
            }
        });

        jlFuncoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlFuncoesMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jlFuncoes);

        javax.swing.GroupLayout jpFuncoesLayout = new javax.swing.GroupLayout(jpFuncoes);
        jpFuncoes.setLayout(jpFuncoesLayout);
        jpFuncoesLayout.setHorizontalGroup(
            jpFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncoesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jbTelaFuncao))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jpFuncoesLayout.setVerticalGroup(
            jpFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbTelaFuncao)
                .addContainerGap())
        );

        jpEstados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Estados");

        jbTelaEstado.setText("Inserir");
        jbTelaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTelaEstadoActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlEstados);

        javax.swing.GroupLayout jpEstadosLayout = new javax.swing.GroupLayout(jpEstados);
        jpEstados.setLayout(jpEstadosLayout);
        jpEstadosLayout.setHorizontalGroup(
            jpEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstadosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTelaEstado))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jpEstadosLayout.setVerticalGroup(
            jpEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTelaEstado)
                .addContainerGap())
        );

        jpAlfabeto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Alfabetos");

        jLabel11.setText("Alfabetos");

        jLabel12.setText("Alfabetos Auxiliares");

        jlAlfabetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAlfabetosMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jlAlfabetos);

        jScrollPane6.setViewportView(jlAuxiliares);

        jbInserirAlfabeto.setText("Inserir");
        jbInserirAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirAlfabetoActionPerformed(evt);
            }
        });

        jbDefinirAlfabetoAuxiliar.setText("Modificar");
        jbDefinirAlfabetoAuxiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDefinirAlfabetoAuxiliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAlfabetoLayout = new javax.swing.GroupLayout(jpAlfabeto);
        jpAlfabeto.setLayout(jpAlfabetoLayout);
        jpAlfabetoLayout.setHorizontalGroup(
            jpAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlfabetoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAlfabetoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbInserirAlfabeto)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDefinirAlfabetoAuxiliar)
                    .addComponent(jLabel12))
                .addGap(40, 40, 40))
        );
        jpAlfabetoLayout.setVerticalGroup(
            jpAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlfabetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAlfabetoLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDefinirAlfabetoAuxiliar)
                        .addContainerGap())
                    .addGroup(jpAlfabetoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbInserirAlfabeto)
                        .addGap(6, 6, 6))))
        );

        jpFita.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Inserir Caractéres na Fita:");

        jbInserirFita.setText("Inserir");
        jbInserirFita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirFitaActionPerformed(evt);
            }
        });

        jbLimparFita.setText("Limpar");
        jbLimparFita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparFitaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Fita");

        javax.swing.GroupLayout jpFitaLayout = new javax.swing.GroupLayout(jpFita);
        jpFita.setLayout(jpFitaLayout);
        jpFitaLayout.setHorizontalGroup(
            jpFitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFitaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpFitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInserirFita, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFitaLayout.createSequentialGroup()
                        .addComponent(jbInserirFita)
                        .addGap(80, 80, 80)
                        .addComponent(jbLimparFita))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFitaLayout.setVerticalGroup(
            jpFitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfInserirFita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpFitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserirFita)
                    .addComponent(jbLimparFita))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpFuncoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpAlfabeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpFita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTuringMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpTuringMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpFita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpEstados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpFuncoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpAlfabeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirFitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirFitaActionPerformed
//        maquina.Inicializar(jtfInserirFita.getText().toCharArray());
//        jbInserirFita.setEnabled(false);
//        jbLimparFita.setEnabled(true);
//        jtfInserirFita.setEditable(false);
//        //start();
    }//GEN-LAST:event_jbInserirFitaActionPerformed

    private void jbLimparFitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparFitaActionPerformed
        start();
    }//GEN-LAST:event_jbLimparFitaActionPerformed

    private void jbTelaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTelaEstadoActionPerformed
        CreateState telaCriarEstado = new CreateState(this, this, rootPaneCheckingEnabled, listaEstados);
        telaCriarEstado.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jbTelaEstadoActionPerformed

    private void jbInserirAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirAlfabetoActionPerformed
        AddAlphabet telaAdicionarAlfabeto = new AddAlphabet(this, this, rootPaneCheckingEnabled, alfabetos);
        telaAdicionarAlfabeto.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jbInserirAlfabetoActionPerformed

    private void jbTelaFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTelaFuncaoActionPerformed
        CreateFunction telaCriarFuncao = new CreateFunction(this, this, rootPaneCheckingEnabled, listaFuncoes, listaEstados, alfabetos);
        telaCriarFuncao.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jbTelaFuncaoActionPerformed

    private void jbDefinirAlfabetoAuxiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDefinirAlfabetoAuxiliarActionPerformed
        AddAuxiliaryAlphabets telaAlfabetosAuxiliares = new AddAuxiliaryAlphabets(this, this, rootPaneCheckingEnabled, alfabetos);
        telaAlfabetosAuxiliares.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jbDefinirAlfabetoAuxiliarActionPerformed

    private void jlFuncoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFuncoesMouseEntered

    }//GEN-LAST:event_jlFuncoesMouseEntered

    private void jlAlfabetosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAlfabetosMouseEntered

    }//GEN-LAST:event_jlAlfabetosMouseEntered

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_jbBuscarActionPerformed

    public void start() {
//        try {
//            maquina.executarMaquina();
//            populateLists();
//            populateTable();
//        } catch (RuntimeException e) {
//            if (e.toString().equals("java.lang.RuntimeException: error")) {
//                GUIMessage.error("Palavra rejeitada!");
//                jbLimparFita.setEnabled(false);
//            }
//            if (e.toString().equals("java.lang.RuntimeException: inf")) {
//                GUIMessage.inf("O Programa entrou em estado de aceitação!");
//                jbLimparFita.setEnabled(false);
//            }
//        }
    }

    public void populateLists() {
//        list_cabecote.clear();
//        list_fita.clear();
//        char[] temp_fita = maquina.getFita();
//        for (int count = 0; count < temp_fita.length; count++) {
//            list_fita.addElement(temp_fita[count]);
//            if (maquina.getCabecote() == count) {
//                list_cabecote.addElement("<--  " + maquina.getEstado());
//            } else {
//                list_cabecote.addElement(" ");
//            }
//        }
    }

//    public void populateTable() {
//        DefaultTableModel model = (DefaultTableModel) jtTabela.getModel();
//        model.setRowCount(0);
//        String[][] temp_historico = maquina.getHistorico();
//        for (int count = 0; count < 9; count++) {
//            model.addRow(new Object[]{"q" + count,
//                temp_historico[count][0],
//                temp_historico[count][1],
//                temp_historico[count][2],
//                temp_historico[count][3],
//                temp_historico[count][4],
//                temp_historico[count][5], /*temp_hijbTelaEstado*/});
//
//        }
//    }
    public void atualizarEstados() {
        mlist_estados.clear();
        if (!listaEstados.isEmpty()) {
            for (int count = 0; count < listaEstados.size(); count++) {
                mlist_estados.addElement(listaEstados.get(count));
            }
        }
    }

    public void atualizarFuncoes() {
        mlist_funcoes.clear();
        if (!listaFuncoes.isEmpty()) {
            for (int count = 0; count < listaFuncoes.size(); count++) {
                Funcao temp_func = listaFuncoes.get(count);
                String atualEstado = temp_func.getEstadoAtual();
                String proxEstado = temp_func.getEstadoProximo();
                String escreve = temp_func.getEscreve();
                String direcao = temp_func.getDirecao();
                mlist_funcoes.addElement("(" + atualEstado + ") " + "(" + proxEstado + "," + escreve + "," + direcao + ")");
            }
        }
    }

    public void atualizarAlfabetos() {
        mlist_alfabetos.clear();
        List<String> temp_listaAlfabetos = alfabetos.getAlfabetos();
        if (!temp_listaAlfabetos.isEmpty()) {
            for (int count = 0; count < temp_listaAlfabetos.size(); count++) {
                mlist_alfabetos.addElement(temp_listaAlfabetos.get(count));
            }
        }
        popularColunasTabela();
    }

    public void atualizarAuxiliares() {
        mlist_alfabetosAuxiliares.clear();
        mlist_alfabetosAuxiliares.addElement(alfabetos.getInicio());
        mlist_alfabetosAuxiliares.addElement(alfabetos.getVazio());
        List<String> temp_auxAlfabetos = alfabetos.getAuxiliares();
        for (int count = 0; count < temp_auxAlfabetos.size(); count++) {
            mlist_alfabetosAuxiliares.addElement(temp_auxAlfabetos.get(count));
        }
        popularColunasTabela();
    }

    public void atualizarFita() {

    }

    public void popularColunasTabela() {
        if (!alfabetos.getAlfabetos().isEmpty() && !alfabetos.getAuxiliares().isEmpty()) {
            jlTabelaColunas = new ArrayList<>();

            model.setColumnCount(0);
            model.addColumn("Estado");
            model.addColumn(alfabetos.getInicio());
            jlTabelaColunas.add(alfabetos.getInicio());

            List<String> temp_listaAlfabetos = alfabetos.getAlfabetos();
            for (int count = 0; count < temp_listaAlfabetos.size(); count++) {
                model.addColumn(temp_listaAlfabetos.get(count));
                jlTabelaColunas.add(temp_listaAlfabetos.get(count));
            }

            List<String> temp_listaAuxiliares = alfabetos.getAuxiliares();
            for (int count = 0; count < temp_listaAuxiliares.size(); count++) {
                model.addColumn(temp_listaAuxiliares.get(count));
                jlTabelaColunas.add(temp_listaAuxiliares.get(count));
            }

            model.addColumn(alfabetos.getVazio());
            jlTabelaColunas.add(alfabetos.getVazio());
            
            for (int count = 0; count< jlTabelaColunas.size();count++){
                System.out.println(count+" :"+ jlTabelaColunas.get(count));
            }
        }
    }

    public void atualizarTabela() {
        if ((alfabetos.getAlfabetos().size() + alfabetos.getAuxiliares().size() + 2) < 15) {
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDefinirAlfabetoAuxiliar;
    private javax.swing.JButton jbInserirAlfabeto;
    private javax.swing.JButton jbInserirFita;
    private javax.swing.JButton jbLimparFita;
    private javax.swing.JButton jbTelaEstado;
    private javax.swing.JButton jbTelaFuncao;
    private javax.swing.JList<String> jlAlfabetos;
    private javax.swing.JList<String> jlAuxiliares;
    private javax.swing.JList<String> jlEstados;
    private javax.swing.JList<String> jlFuncoes;
    private javax.swing.JPanel jpAlfabeto;
    private javax.swing.JPanel jpBuscas;
    private javax.swing.JPanel jpEstados;
    private javax.swing.JPanel jpFita;
    private javax.swing.JPanel jpFuncoes;
    private javax.swing.JPanel jpTuringMachine;
    private javax.swing.JTable jtFita;
    private javax.swing.JTable jtTabela;
    private javax.swing.JTextField jtfBuscarFrase;
    private javax.swing.JTextField jtfInserirFita;
    // End of variables declaration//GEN-END:variables
}
