/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turing.machine;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicios
 */
public class Tela extends javax.swing.JFrame {

    private DefaultListModel list_fita;
    private DefaultListModel list_cabecote;
    TuringMachine maquina = new TuringMachine();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();

        list_fita = new DefaultListModel();
        list_cabecote = new DefaultListModel();
        jlFita.setModel(list_fita);
        jlCabecote.setModel(list_cabecote);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jtfCaracteres = new javax.swing.JTextField();
        jbInicio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlFita = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlCabecote = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbInicio.setText("Iniciar");
        jbInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInicioActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlFita);

        jScrollPane3.setViewportView(jlCabecote);

        jtTabela.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"q0", null, null, null, null, null, null},
                {"q1", null, null, null, null, null, null},
                {"q2", null, null, null, null, null, null},
                {"q3", null, null, null, null, null, null},
                {"q4", null, null, null, null, null, null}
            },
            new String [] {
                "Estado", "*", "a", "b", "A", "B", "β"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabela.setOpaque(false);
        jtTabela.setRowSelectionAllowed(false);
        jtTabela.setShowHorizontalLines(false);
        jScrollPane4.setViewportView(jtTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbInicio)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbInicio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInicioActionPerformed
        maquina.Inicializar(jtfCaracteres.getText().toCharArray());
        executarMaquina();
        jbInicio.setEnabled(false);
    }//GEN-LAST:event_jbInicioActionPerformed

    public void executarMaquina() {
        populateLists();
        try {
            while (true) {

                Thread.sleep(100);
                char[] a = maquina.getFita();
                char maq_letra = maquina.Ler();
                System.out.println("Cabeçote: " + maquina.getCabecote());
                System.out.println("Estado atual: " + maquina.getEstado());
                for (int count = 0; count < a.length; count++) {
                    System.out.println("Array: " + a[count]);
                }
                if (maquina.getEstado().equals("q0")) {
                    maquina.setEstado(maquina.q0(maq_letra));
                } else if (maquina.getEstado().equals("q1")) {
                    maquina.setEstado(maquina.q1(maq_letra));
                } else if (maquina.getEstado().equals("q2")) {
                    maquina.setEstado(maquina.q2(maq_letra));
                } else if (maquina.getEstado().equals("q3")) {
                    maquina.setEstado(maquina.q3(maq_letra));
                } else if (maquina.getEstado().equals("q4")) {
                    System.out.println(maquina.q4(maq_letra));
                    break;
                } else {
                    System.out.println(maquina.qe(maq_letra));
                    break;
                }
            }
        } catch (InterruptedException e) {

        }
    }

    public void populateLists() {
        list_cabecote.clear();
        list_fita.clear();
        char[] temp_fita = maquina.getFita();
        for (int count = 0; count < temp_fita.length; count++) {
            list_fita.addElement(temp_fita[count]);
            if (maquina.getCabecote() == count) {
                list_cabecote.addElement("<--  " + maquina.getEstado());
            } else {
                list_cabecote.addElement(" ");
            }
        }
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jtTabela.getModel();

        model.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbInicio;
    private javax.swing.JList<String> jlCabecote;
    private javax.swing.JList<String> jlFita;
    private javax.swing.JTable jtTabela;
    private javax.swing.JTextField jtfCaracteres;
    // End of variables declaration//GEN-END:variables
}
